spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OAUTH_JWKS_URI:http://localhost:8083/oauth/jwks}
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: 27017
      database: ${MONGO_NAME:store-db}
      username: ${MONGO_INITDB_ROOT_USERNAME:root}
      password: ${MONGO_INITDB_ROOT_PASSWORD:profectcloud}
      authentication-database: admin

    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:password}
      database: 0

  kafka:
    bootstrap-servers:
      - ${KAFKA_URL1:localhost:9092}
      - ${KAFKA_URL2:localhost:9094}
      - ${KAFKA_URL3:localhost:9096}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      enable-idempotence: true
      retries: 2
      acks: all
      properties:
        max.in.flight.requests.per.connection: 3
        min.insync.replicas: 2
    admin:
      auto-create: true

jwt:
  audience:  ${AUTH_INTERNAL_AUDIENCE:internal-services}

discord:
  webhook:
    url: ${DISCORD_URL}
