spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OAUTH_JWKS_URI:http://localhost:8083/oauth/jwks}
  application:
    name: store
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL:localhost:5432}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: 27017
      database: ${MONGO_NAME:store-db}
      username: ${MONGO_INITDB_ROOT_USERNAME:root}
      password: ${MONGO_INITDB_ROOT_PASSWORD:profectcloud}
      authentication-database: admin
  batch:
    job:
      enabled=false:
    jdbc:
      initialize-schema: ALWAYS
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG


jwt:
  audience:  ${AUTH_INTERNAL_AUDIENCE:internal-services}

discord:
  webhook:
    url: ${DISCORD_URL:https://discord.com/api/webhooks/1406866286629355540/Y4r06Y2UIA5IjkrG_JqWC1P_u0xC9GuTmdR0N-ji6eQiuNDsyu_wToA0RcEAjhlWpSEU}
server:
  port: 8082