spring:
  application:
    name: store
  config:
    import: optional:file:.env[.properties]

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true

server:
  port: 8082